# Changes here will be overwritten by Copier
AnswerStrategy: recommended
AuthorEmail: miguelraz@gmail.com
AuthorName: Miguel Raz
Indentation: 4
JuliaMinVersion: '1.10'
License: MIT
PackageName: RustCall
PackageOwner: miguelraz
PackageUUID: 21f8330c-064f-59a2-a8b1-2ab86cccd9f6
_commit: v0.9.0
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
